version: '3.8'
services:
  patient:
    image: 8889docker/patient-app:0.0.1
    container_name: patient-app
    ports:
      - "8080:8080"
    networks:
      - patient-network

networks:
  patient-network:
    driver: bridge